% From joint distribution, compute marginal distribution.
% Also reads the transform matrices from input parameter joint_to_margin,
% which can be generated by JoinToMargin.m.
% Support GVar input.

function [alph_x, alph_y, alph_z] = MarginalDist(alph, joint_to_margin)
  alph_x = alph * joint_to_margin{1};
  alph_y = alph * joint_to_margin{2};
  alph_z = alph * joint_to_margin{3};
end
